### Obtener todos los usuarios (GET)
GET https://m3.1rodemayo.com/api/user
Accept: application/json

###

### Obtener un usuario por ID (GET)
GET https://m3.1rodemayo.com/api/user/1
Accept: application/json

###

### Crear un nuevo usuario (POST)
POST https://m3.1rodemayo.com/api/user
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@example.com"
}

###

### Actualizar un usuario existente (PUT)
PUT https://m3.1rodemayo.com/api/user/1
Content-Type: application/json

{
  "name": "John Updated",
  "email": "johnupdated@example.com"
}

###

### Eliminar un usuario por ID (DELETE)
DELETE https://m3.1rodemayo.com/api/user/1
